from pydantic import BaseModel, Field
from typing import List, Optional

class HintRequest(BaseModel):
    question_text: str = Field(description="The question prompt the candidate is currently answering")
    expected_keywords: List[str] = Field(description="The keywords expected in a correct answer")
    chat_history: Optional[List[dict]] = Field(default=[], description="Previous message exchange in this question's chat panel")

class HintResponse(BaseModel):
    hint: str = Field(description="The subtle hint generated by the AI interviewer")
